### ISSUE TITLE
Consider supporting building with an external copy of uthash

### ISSUE THREAD

**Issue by bgilbert** [hackermd/libdicom#16]
Many Linux distributions discourage packages from including bundled copies of other packages (e.g. [Debian policy](https://www.debian.org/doc/debian-policy/ch-source.html#embedded-code-copies), [Fedora policy](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling)).  However, there's often a formal or informal exception for libraries that are designed to be copied directly into another codebase ("copylibs").  uthash [is such a package](https://troydhanson.github.io/uthash/userguide.html#_is_it_a_library).

Nevertheless, it would be nice to optionally allow building with an external copy of uthash, rather than the one provided with libdicom.  Both [Debian](https://packages.debian.org/bullseye/uthash-dev) and [Fedora](https://packages.fedoraproject.org/pkgs/uthash/) provide such a package.

**Comment by hackermd** [comment]
Agreed! Detecting and using existing uthash headers would be a good idea.
