### ISSUE TITLE
Add pkg-config file

### ISSUE THREAD

**Issue by bgilbert** [hackermd/libdicom#20]
Install a [pkg-config](https://people.freedesktop.org/~dbn/pkg-config-guide.html) file to help library users find the library at compile time.

**Comment by jcupitt** [comment]
I'm adding a meson build system right now, so this should pop out automatically.

**Comment by bgilbert** [comment]
It turns out we were both working on Meson conversions in parallel.  We discussed this OOB and I'm going to post a PR soon.
